name: dartodef
version: 0.1.0
author: Eric Schneller <eric@schnellers.name>
description: |-
  Set variable values in compile time. Set the environment variable DARTODEF
  to define which property of the map defined in the pubspec.yaml should be used.
dependencies:
  analyzer: any
  barback: any
  source_maps: any
